version: '3.8'
services:
  api:
    build: 
     context: ./api
    ports:
      - '80:80'
  client:
    build:
      context: ./frontend
    ports:
      - '8501:8501'






#docker-compose up to run the docker file