version: '3.8'
services:
  api:
    build: 
     context: ./api
    ports:
      - '80:80'
    volumes: 
      - ./api:/app
  client:
    build:
      context: ./frontend
    ports:
      - '8501:8501'
    volumes: 
      - ./frontend:/frontend
    depends_on:
      - api





#docker-compose up to run the docker file